title: FUNdamental Initiative
email: insertEmail
description: FUNdamental - towards international consensus on transcranial focused ultrasonic neurostimulation

baseurl: "/"                                # the subpath of your site, e.g. /blog
url: "https://www.fundatus.github.io"      # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benjamin_kop
github_username:  benjamin-kop

excerpt_separator: <!--more-->

# Build settings
sass:
  sass_dir: ./assets/css

# see https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      toc: false
      sitemap: false
  -
    scope:
      path: "development/project"
      type: "pages"
    values:
      sitemap: false
  -
    scope:
      path: "development/meeting"
      type: "pages"
    values:
      sitemap: false
  -
    scope:
      path: "tag"
      type: "pages"
    values:
      sitemap: false

toc:
  min_level: 2 # default: 1
  max_level: 4 # default: 6

permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: matlab
plugins:
  - jekyll-last-modified-at
  - jekyll-toc          # https://github.com/toshimaru/jekyll-toc
  - jekyll-sitemap      # https://github.com/jekyll/jekyll-sitemap
  - jekyll-redirect-from # https://blog.webjeda.com/jekyll-redirect/

exclude:
  - README.md
  - COPYING.md
  - Gemfile*
